import { expect, test } from '@playwright/test'

const email = process.env.E2E_EMAIL
const password = process.env.E2E_PASSWORD
const runFullJourney = process.env.E2E_FULL === 'true' && Boolean(email && password)

test('parcours réel Responsable Opérations', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop-chromium', 'Le parcours métier est joué une seule fois.')
  test.skip(!runFullJourney, 'E2E_FULL, E2E_EMAIL et E2E_PASSWORD sont requis.')

  const suffix = Date.now().toString().slice(-8)
  const clientName = `Client E2E ${suffix}`
  const carrierName = `Transporteur E2E ${suffix}`
  const incidentTitle = `Incident E2E ${suffix}`

  await page.goto('/login')
  await page.getByLabel('Adresse e-mail').fill(email!)
  await page.getByLabel('Mot de passe').fill(password!)
  await page.getByRole('button', { name: 'Se connecter' }).click()
  await expect(page).toHaveURL(/\/o\/[^/]+\/operations\/?$/)

  const operationsRoot = new URL(page.url()).pathname.replace(/\/$/, '')

  await page.goto(`${operationsRoot}/clients`)
  await expect(page.getByRole('heading', { name: 'Clients' })).toBeVisible()
  await page.getByRole('button', { name: /Ajouter un client/ }).click()
  await page.getByLabel('Nom').fill(clientName)
  await page.getByLabel('Personne à contacter').fill('Contact E2E')
  await page.getByLabel('Téléphone').fill(`0700${suffix}`)
  await page.getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText(clientName)).toBeVisible()

  await page.goto(`${operationsRoot}/transporteurs`)
  await expect(page.getByRole('heading', { name: 'Transporteurs' })).toBeVisible()
  await page.getByRole('button', { name: 'Ajouter un transporteur' }).click()
  await page.locator('#carrier-name').fill(carrierName)
  await page.locator('#carrier-phone').fill(`0500${suffix}`)
  await page.locator('#carrier-trucks').fill('Porteur 10T')
  await page.locator('#carrier-destinations').fill('Bouaké')
  await page.getByRole('dialog').getByRole('button', { name: 'Ajouter', exact: true }).click()
  await expect(page.getByText(carrierName)).toBeVisible()

  await page.goto(`${operationsRoot}/needs/new`)
  await expect(page.getByRole('heading', { name: 'Créer un besoin opérationnel' })).toBeVisible()
  await page.locator('#need-client').selectOption({ label: clientName })
  await page.locator('#need-urgency').selectOption('HIGH')
  await page.locator('#need-truck-type').fill('Porteur 10T')
  await page.locator('#need-requested').fill('2')
  await page.locator('#need-tonnage').fill('10')
  await page.locator('#need-cargo').fill('Matériel E2E')
  await page.locator('#need-loading').fill('Abidjan')
  await page.locator('#need-destination').fill('Bouaké')
  await page.locator('#need-mobilization').fill('2026-08-01T08:00')
  await page.getByRole('button', { name: 'Publier le besoin' }).click()

  await expect(page).toHaveURL(/\/needs\/[^/]+$/)
  await expect(page.getByText('Ouvert', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Ajouter une option' }).click()
  await page.locator('#option-carrier-id').selectOption({ label: carrierName })
  await page.locator('#option-count').fill('2')
  await page.locator('#option-price').fill('850000')
  await page.locator('#option-available').fill('2026-08-01T06:30')
  await page.locator('label').filter({ hasText: 'Carte grise' }).click()
  await page.locator('#option-notes').fill('Option complète vérifiée par le test E2E.')
  await page.getByTestId('carrier-option-submit-top').click()
  await expect(page.getByText(carrierName)).toBeVisible()
  await expect(page.getByText('À vérifier')).toBeVisible()

  await page.getByRole('link').filter({ hasText: carrierName }).filter({ hasText: 'OPT-' }).click()
  await expect(page).toHaveURL(/\/options\/[^/]+$/)
  await expect(page.getByRole('button', { name: 'Accepter' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Valider la conformité' }).click()
  await expect(page.getByText('Option contrôlée par le superviseur')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Accepter' })).toBeVisible()
  await page.getByRole('button', { name: 'Accepter' }).click()
  await page.locator('#accepted-count').fill('2')
  await page.locator('#accept-note').fill('Acceptation automatisée E2E.')
  await page.getByRole('button', { name: 'Confirmer et créer la mission' }).click()
  await expect(page.getByText('Option acceptée')).toBeVisible()
  await expect(page.getByText('Mission créée')).toBeVisible()

  await page.getByRole('button', { name: 'Voir les missions' }).click()
  await expect(page).toHaveURL(/\/missions$/)
  await page.locator('#missions-search').fill(carrierName)
  await expect(page.getByText(carrierName)).toBeVisible()
  await page.getByRole('link', { name: /Détail/ }).click()
  await expect(page).toHaveURL(/\/missions\/[^/]+$/)
  await page.getByRole('button', { name: 'Mettre à jour le statut' }).click()
  await page.locator('#mission-location').fill('Abidjan - Zone industrielle')
  await page.locator('#mission-note').fill('Mobilisation validée par le test E2E.')
  await page.getByRole('button', { name: 'Confirmer' }).click()
  await expect(page.getByText('Statut de mission mis à jour')).toBeVisible()
  await expect(page.getByText('Mobilisation')).toBeVisible()
  const missionReference = (await page.locator('h1').textContent())?.trim()
  expect(missionReference).toMatch(/^MS-/)

  await page.goto(`${operationsRoot}/incidents`)
  await expect(page.getByRole('heading', { name: 'Incidents' })).toBeVisible()
  await page.getByRole('button', { name: 'Déclarer un incident' }).click()
  await page.locator('#incident-title').fill(incidentTitle)
  await page.locator('#incident-description').fill('Vérification automatisée du workflow incident.')
  await page.locator('#incident-severity').selectOption('HIGH')
  await page.locator('#incident-mission').selectOption({ label: `${missionReference} · Bouaké` })
  await page.getByRole('dialog').getByRole('button', { name: 'Déclarer', exact: true }).click()
  await expect(page.getByText(incidentTitle)).toBeVisible()
  await expect(page.getByText(missionReference!)).toBeVisible()
  await page.getByRole('button', { name: 'Traiter' }).click()
  await page.locator('#incident-action-status').selectOption('RESOLVED')
  await page.locator('#incident-resolution').fill('Résolu pendant la vérification E2E.')
  await page.getByRole('button', { name: 'Mettre à jour' }).click()
  await expect(page.getByText('Incident mis à jour')).toBeVisible()
  await expect(page.getByText('Résolu')).toBeVisible()

  await page.goto(`${operationsRoot}/transporteurs`)
  await page.locator('#carrier-search').fill(carrierName)
  await expect(page.getByText(carrierName)).toBeVisible()
  await expect(page.locator(`a[href^="tel:+2250500${suffix}"]`)).toHaveCount(2)
  await expect(page.locator(`a[href^="https://wa.me/2250500${suffix}"]`)).toHaveCount(1)
  await page.getByRole('link', { name: 'Ouvrir' }).click()
  await expect(page).toHaveURL(/\/transporteurs\/[^/]+$/)
  await page.getByRole('button', { name: 'Ajouter' }).click()
  await page.locator('#vehicle-registration').fill(`E2E-${suffix}`)
  await page.locator('#vehicle-type').fill('Porteur 10T')
  await page.locator('#vehicle-capacity').fill('10')
  await page.getByRole('dialog').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText(`E2E-${suffix}`)).toBeVisible()
  await page.getByRole('button', { name: 'Mettre à jour' }).click()
  await page.locator('#availability-location').fill('Bouaké')
  await page.locator('#availability-notes').fill('Disponible confirmé par E2E.')
  await page.getByRole('dialog').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText('Disponible')).toBeVisible()
  await page.getByRole('button', { name: 'Journaliser un appel' }).click()
  await page.locator('#call-outcome').selectOption('AVAILABLE')
  await page.locator('#call-notes').fill('Transporteur disponible, appel validé E2E.')
  await page.getByRole('dialog').getByRole('button', { name: 'Enregistrer' }).click()
  await expect(page.getByText('Disponible')).toBeVisible()
  await expect(page.getByText('Transporteur disponible, appel validé E2E.')).toBeVisible()

  await page.goto(`${operationsRoot}/rapports`)
  await expect(page.getByRole('heading', { name: 'Rapports' })).toBeVisible()
  await expect(page.getByText('Performance agents')).toBeVisible()
  await expect(page.getByText('Incidents ouverts')).toBeVisible()
})
